### ISSUE TITLE
Export registrations as CSV ?

### ISSUE THREAD

**Issue by sylvainar** [dpi/rng#129]
Hey !

Is it possible to export the list of people who have registered on a event as a CSV file?

Thanks !

PS: Congrats for the 1.3 :wink:

**Comment by dpi** [comment]
RNG has full views integration from event entity to registration to individual registrant entities. The views submodule can get you started there.

As for CSV you would attach a CSV display mode from the [views_data_export](https://www.drupal.org/project/views_data_export) project to one of the views generated by the submodule.

Hope this helps.

**Comment by sylvainar** [comment]
Awesome, thanks !
