### ISSUE TITLE
Registration create/update triggers are not executing

### ISSUE THREAD

**Issue by buntybatra** [dpi/rng#139]
Hi,

I am using the RNG module for registration. All the things working fine except the email on "Registration creation". Message "Send on a date" is working fine. Following is the configuration:-

Registration creation (active)
Courier module version alpha-9

Please tell me if i am missing some configuration.

Thanks

**Comment by dpi** [comment]
Thanks @buntybatra , I have verified the issue. A fix will be coming in the next few days.

**Comment by buntybatra** [comment]
Thanks @dpi for quick response. I am waiting for fix

**Comment by dpi** [comment]
Fix is in rng 8.x-1.5-alpha1

**Comment by dpi** [comment]
Stable release 1.5 is out.
