### ISSUE TITLE
Content Moderation and RNG throw an exception

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [dpi/rng#142]
I enabled the experimental module named "[Content Moderation](https://www.drupal.org/docs/8/core/modules/content-moderation)" on Drupal 8.3 instance, then when I am trying to access to "Event" tab into any content type (basically access to [rng.event.$entity_type.event.default](https://github.com/dpi/rng/blob/8.x-1.x/src/Plugin/Derivative/LocalTasks.php#L83) router, it throws me the following exception,

> Error: Call to undefined method Drupal\rng\Form\EventSettingsForm::getEntity() in Drupal\content_moderation\Plugin\Field\FieldWidget\ModerationStateWidget::processActions() (line 183 of core/modules/content_moderation/src/Plugin/Field/FieldWidget/ModerationStateWidget.php).

I noticed that "ModerationStateWidget::processActions" at line 183 is trying to access to an entity,
> $entity = $form_state->getFormObject()->getEntity();

Perhaps you should either implement that method into "EventSettingsForm" or setup an validation into "ModerationStateWidget::processActions" method, something like this:
```
    if(!method_exists($form_state->getFormObject(), 'getEntity')) {
      return;
    }
    $entity = $form_state->getFormObject()->getEntity();
```

**Comment by kenneth-bolivar-castro** [comment]
Since I wasn't unsure where this case should be address, I added an issue into drupal core queue,
https://www.drupal.org/node/2871627

**Comment by dpi** [comment]
Thanks for the report, it looks to be a bug with content_moderation module. I have replied with rationale in https://www.drupal.org/node/2871627
