### ISSUE TITLE
Simplified Registration

### ISSUE THREAD

**Issue by bitchkat** [dpi/rng#146]
I have a use case where the only type of registrations allowed will be anonymous users.  However I think the UI is going to be way to confusing for the users.  I also just have a single rng_contact type.

Can I simplify the UI to the point that we effectively just have the rng_contact form and a single submit button that creates the rng contact and registers it to the event?

**Comment by dpi** [comment]
You are more than welcome to create your own UI/forms. I encourage it. Keeping in mind that it is unlikely to be brought into the main module per https://github.com/dpi/rng/wiki/Solid-Core

Inspiration can be found from [RNG Quick](https://drupal.org/project/rng_quick), as it implements two of its own registration forms.

Ensure you are maintaining the RNG model by using the `EventMeta` systems.

**Comment by dpi** [comment]
If you are looking for reviews/architecture/sanity-checks; I'm happy to help.

**Comment by bitchkat** [comment]
Thanks.  I have no problem with it not being in your rng.  I'm quite fine doing it in a custom module and I'll use RNG Quick for inspiration.

**Comment by ehardeveld** [comment]
We also need an simplified interface for anonymous registrations. @bitchkat, can you publish your work? We are willing to collaborate where possible if you like that. Otherwise we will create and publish our own implementation.

**Comment by bitchkat** [comment]
@ehardeveld sorry for the delay in responding as I was out of the country with poor internet.  I put this off for a bit to get other aspects of the website finished.  I've been working on it this past week and have made some progress. The approach I've taken is to basically fork rng_quick.  What I've done is replace the RngQuickFormBlock.php with my own custom form, validation handler, and submit handler.

What I'm doing is using rng_contact to manage registrations for anonymous users.  In my quick form, I collect the same info that would be in the rng_contact entity.  For example, my rng_contact type is called visitors and I collect a name, email address, company, and phone number.  

This website also has the need where an event may have multiple sessions.  Think of a conference where there are multiple seminars going on every hour.   On the quick form, I display a list of all the sessions available for the main event and group them by start time.  Then they select sessions they would like to attend with restrictions like they can only attend one at a given time.  

When they submit the form, I create the rng_contact.  I'm contemplating looking up an existing contact that matches email address, name and possibly some of the other contact info.  However, since this can be submitted by anonymous users I want to be careful about that.

After the contact is created, I then register them for the main event and finally loop through the sessions they selected and register them for those.  Well at least that is what I'm currently working on.

The code in its current form is pretty site specific as it assumes the following:

1. An event may have associated sessions.  Assumes my session content type.
2. The quick form is hard coded.  If there is an easy way to generate a form for a particular rng_contact, that could be a decent replacement.  But the standard rng_quick UI is pretty awful.
3.  In formatting my session start times, I have a quick and dirty hard coding of the time zone. 
4. Form validation is of course specific to my form.
5. Creating the rng_contact is hard coded to the rng_contact bundle I created.
6. Of course the session registration is specific to my set up.

I'm happy to share the code with you.  I'll probably have something reasonably working (for this particular site) in a few days and we can figure out the best way to share it.  Let me know if you're still interested or if you've made any progress on your own.

**Comment by ehardeveld** [comment]
@bitchkat, Thanks for your extensive response! I am still interested but my project is delayed a bit. I think your approach would also work for my website, so I can clone rng_quick and adopt it to my needs. If you could share your code I can also base it on your code.
