### ISSUE TITLE
Drupal 8, Error after saving event.

### ISSUE THREAD

**Issue by druplash** [dpi/rng#148]
After adding registration and registrant types i have add the first event. After editing everything in tab „Event“ i click save and get the following error. Please can somebody take a look? I do not understand what is going wrong. It seems to be a bug...

> Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'registrant.registration_int' in 'on clause': SELECT base_table.id AS id, base_table.id AS base_table_id FROM {registrant} base_table INNER JOIN {registrant} registrant ON registrant.id = base_table.id LEFT OUTER JOIN {registration} registration ON registration.id = registrant.registration_int INNER JOIN {registration_field_data} registration_field_data ON registration_field_data.id = registration.id LEFT OUTER JOIN {registration} registration_2 ON registration_2.id = registrant.registration_int WHERE (registration_field_data.event__target_type = :db_condition_placeholder_0) AND (registration_field_data.event__target_id = :db_condition_placeholder_1) AND (registrant.identity__target_type = :db_condition_placeholder_2); Array ( [:db_condition_placeholder_0] => node [:db_condition_placeholder_1] => 9 [:db_condition_placeholder_2] => user ) in Drupal\rng\EventMeta->getRegistrants() (line 428 of modules/rng/src/EventMeta.php).
> Drupal\Core\Database\Statement->execute(Array, Array) (Line: 624)
> Drupal\Core\Database\Connection->query('SELECT base_table.id AS id, base_table.id AS base_table_id
> FROM 
> {registrant} base_table
> INNER JOIN {registrant} registrant ON registrant.id = base_table.id
> LEFT OUTER JOIN {registration} registration ON registration.id = registrant.registration_int
> INNER JOIN {registration_field_data} registration_field_data ON registration_field_data.id = registration.id
> LEFT OUTER JOIN {registration} registration_2 ON registration_2.id = registrant.registration_int
> WHERE (registration_field_data.event__target_type = :db_condition_placeholder_0) AND (registration_field_data.event__target_id = :db_condition_placeholder_1) AND (registrant.identity__target_type = :db_condition_placeholder_2)', Array, Array) (Line: 87)
> Drupal\Core\Database\Driver\mysql\Connection->query('SELECT base_table.id AS id, base_table.id AS base_table_id
> FROM 
> {registrant} base_table
> INNER JOIN {registrant} registrant ON registrant.id = base_table.id
> LEFT OUTER JOIN {registration} registration ON registration.id = registrant.registration_int
> INNER JOIN {registration_field_data} registration_field_data ON registration_field_data.id = registration.id
> LEFT OUTER JOIN {registration} registration_2 ON registration_2.id = registrant.registration_int
> WHERE (registration_field_data.event__target_type = :db_condition_placeholder_0) AND (registration_field_data.event__target_id = :db_condition_placeholder_1) AND (registrant.identity__target_type = :db_condition_placeholder_2)', Array, Array) (Line: 508)
> Drupal\Core\Database\Query\Select->execute() (Line: 250)
> Drupal\Core\Entity\Query\Sql\Query->result() (Line: 77)
> Drupal\Core\Entity\Query\Sql\Query->execute() (Line: 428)
> Drupal\rng\EventMeta->getRegistrants('user') (Line: 79)
> Drupal\rng\Plugin\EntityReferenceSelection\RNGSelectionBase->removeDuplicateRegistrants(Object) (Line: 96)
> Drupal\rng\Plugin\EntityReferenceSelection\RNGSelectionBase->buildEntityQuery(NULL, 'CONTAINS') (Line: 27)
> Drupal\rng\Plugin\EntityReferenceSelection\UserRNGSelection->buildEntityQuery(NULL, 'CONTAINS') (Line: 308)
> Drupal\Core\Entity\Plugin\EntityReferenceSelection\DefaultSelection->countReferenceableEntities() (Line: 515)
> Drupal\rng\EventMeta->countRngReferenceableEntities('user', Array) (Line: 457)
> Drupal\rng\EventMeta->canRegisterProxyIdentities() (Line: 114)
> Drupal\rng\AccessControl\RegistrationAccessControlHandler->createAccess(NULL, Object, Array, 1) (Line: 46)
> Drupal\rng\Access\RegistrationAddAccessCheck->access(Object, Object, Object, NULL)
> call_user_func_array(Array, Array) (Line: 159)
> Drupal\Core\Access\AccessManager->performCheck('access_check.rng.event_registrations_allowed', Object) (Line: 135)
> Drupal\Core\Access\AccessManager->check(Object, Object, NULL, 1) (Line: 92)
> Drupal\Core\Access\AccessManager->checkNamedRoute('rng.event.node.register.type_list', Array, Object, 1) (Line: 327)
> Drupal\Core\Menu\LocalTaskManager->getTasksBuild('rng.event.node.event', Object) (Line: 358)
> Drupal\Core\Menu\LocalTaskManager->getLocalTasks('rng.event.node.event', 0) (Line: 94)
> Drupal\Core\Menu\Plugin\Block\LocalTasksBlock->build() (Line: 203)
> Drupal\block\BlockViewBuilder::preRender(Array)
> call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 376)
> Drupal\Core\Render\Renderer->doRender(Array) (Line: 448)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
> Drupal\Core\Render\Renderer->render(Array) (Line: 490)
> Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 47)
> __TwigTemplate_c4ce23de207dc46e8b855df6ae5bcb5f6ea8ee9d4e68b20374e250ee973aaa66->doDisplay(Array, Array) (Line: 379)
> Twig_Template->displayWithErrorHandling(Array, Array) (Line: 347)
> Twig_Template->display(Array) (Line: 358)
> Twig_Template->render(Array) (Line: 64)
> twig_render_template('core/themes/seven/templates/page.html.twig', Array) (Line: 384)
> Drupal\Core\Theme\ThemeManager->render('page', Array) (Line: 435)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
> Drupal\Core\Render\Renderer->render(Array) (Line: 490)
> Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 90)
> __TwigTemplate_4f9a182f26dee381aaff000213e417cd34f1ab1ad774e966a89a88a6ca5acdb5->doDisplay(Array, Array) (Line: 379)
> Twig_Template->displayWithErrorHandling(Array, Array) (Line: 347)
> Twig_Template->display(Array) (Line: 358)
> Twig_Template->render(Array) (Line: 64)
> twig_render_template('core/themes/classy/templates/layout/html.html.twig', Array) (Line: 384)
> Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 435)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
> Drupal\Core\Render\Renderer->render(Array) (Line: 147)
> Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 574)
> Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 148)
> Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
> Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 111)
> Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 149)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
> Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
> Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
> Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 656)
> Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by dpi** [comment]
Hi @druplash 

There is not supposed to be a `registrant.registration_int` field.

Perhaps there is a third party altering the schema or query in some way?

**Comment by druplash** [comment]
Hi @dpi 
Thanks for reply! I don´t know... I have installed all extra modules (Conflict, Contact, Date Scheduler, Quick) and all Dependencies, nothing else. I will uninstall everything and try it again step by step.

**Comment by druplash** [comment]
@dpi 
I have done a clean install with:

Drupal, 8.3.5
RNG, 8.x-1.5
Dynamic Entity Reference, 8.x-2.0-alpha5
Courier, 8.x-1.0-alpha9
Unlimited Number, 8.x-1.0-beta2

But still getting the same error.
`Unknown column 'registrant.registration_int'`

Do you have any ideas please?
Thanks

**Comment by dpi** [comment]
Why are you using "Dynamic Entity Reference, 8.x-2.0-alpha5" ?

Dont use it when there is a stable version of DER.

**Comment by druplash** [comment]
Sorry @dpi you´re right! I don´t know why... I haven´t realized that i´m using an alpha version. Now it works without any issues. Thanks a lot for helping!

**Comment by jibran** [comment]
There was a bug in 8.x-2.0-alpha4 and it got fixed in 8.x-2.0-alpha5. Just out of curiosity, @druplash if you now update DER to 8.x-2.0-alpha5 after the error is gone, do you see the same problem?

**Comment by druplash** [comment]
@jibran, alpha5 was installed. And there was the error.

**Comment by jibran** [comment]
I meant now that your error is gone can you try 8.x-2.0-alpha5 again? Error was in 8.x-2.0-alpha4, if you update it directly to 8.x-2.0-alpha5 it shouldn't happen.

**Comment by druplash** [comment]
@jibran, ok i will try it. But i´ll be back in office on Monday.

**Comment by dpi** [comment]
> Now it works without any issues.

Do you mean you switched to DER 8.x-1.x?
