### ISSUE TITLE
Add custom message trigger

### ISSUE THREAD

**Issue by norwegianblue-nz** [dpi/rng#149]
This is a support request.
How would I add a message trigger ?
I have a custom module that alters the value of a field in the registration. I would like to trigger a message when that field is updated.
Thanks

**Comment by norwegianblue-nz** [comment]
For anyone who might read this issue and need to do similar, I resorted to the brute-force approach of editing a custom copy of RNG. 
I added a new trigger_id to RngRequestSubscriber
`          case 'update':`
`              if ($registration->get('field_allocated_in_draw')[0]->value > '0'){`
`              $trigger_id = 'entity:registration:drawn';`
`            }`
`            else {`
`            $trigger_id = 'entity:registration:update';`
`            }
`
and then added that trigger into MessageListForm and MessageActionForm:
`      'entity:registration:drawn' => $this->t('Entry drawn'),
`

If there is  a better way of doing this without editing the std RNG classes, then I would be interested to know how, but this has worked for my immediate requirement.

**Comment by dpi** [comment]
Sorry this fell off during my holiday.

Just send any string for `$trigger_id` to, plus appropriate context:

`$event_meta->trigger($trigger_id, ['registrations' => [$registration]]);`

You can alter `rng_event_message_create` form adding your trigger id and a friendly label.
