### ISSUE TITLE
Include Registration states and transitions (like D7 Entity Registration)

### ISSUE THREAD

**Issue by norwegianblue-nz** [dpi/rng#154]
Feature Request
A big improvement would be if there were a system similar to the D7 Entity Registration 'States'
ie site builder determines the valid states of a registration (which might be entered, confirmed, paid, withdrawn etc etc) and there is the 'transistion' system to allow the registrant to move between these states if appropriate (say from paid to withdrawn)

**Comment by dpi** [comment]
Sounds exactly like core Content Moderation.

**Comment by dpi** [comment]
[Workflows Field](https://www.drupal.org/project/workflows_field) may be worth taking a look at also.

I dont think your request is specifically something destined to live in RNG proper.

**Comment by norwegianblue-nz** [comment]
I'm also investigating [State Machine](https://www.drupal.org/project/state_machine) as utilised by Commerce

**Comment by Sam152** [comment]
Workflows field and state machine do pretty much the same thing. Workflows field leverages the new core "workflows" module, whereas state machine has its own config representation of the workflow.

Workflows field might still be somewhat in flux, as there is no tagged release.

**Comment by norwegianblue-nz** [comment]
Workflows Field looks promising, but I need to have a means of making Rng event places available again if a registrant moves their status to withdrawn. Would you see this as something handled by Rules ?

**Comment by dpi** [comment]
I cant really speak for "event places". No-one has developed a generalised waitlist/slot project.

There are max registrations/registrants, etc. But that is not the same. If you want to hijack the max-registrations/maxregistrants system, you could hack the event a registration is associated with to be a different "cancelled meta-event".

On registration entity save, if new_status == 'withdrawn' then $registration->setEvent(mydummyevent)->save();

**Comment by norwegianblue-nz** [comment]
I've sorted this with a custom module.

**Comment by jonathanjfshaw** [comment]
I'd be interested in seeing your custom module, workflows integration is something that interests me.

**Comment by norwegianblue-nz** [comment]
To be clear - my requirements were very specific. It deals with hunters applying by ballot to gain entry to hunting areas (known as blocks) during the rutting season of deer here in NZ.
I could possibly have written things more generically but my D8 dev skills are still a bit limited and I was under some time pressure.
The custom module aspects were quite simple (they have top be as I'm not experienced in D8 modules writing). Probably none adhers to Drupal coding standards either.
Essentially I use workflows and workflows_field module.
I set up the workflow and it's states, but no transitions.
I defined a field 'Status' on the registration type I'm using.
The module then sets / queries the status field as required.
For instance, I have a form which allows the user to accept or withdraw entry to the hunting block they were allocated in the ballot. 
These are the two actions on the form buttons:
```
public function submitForm(array &$form, FormStateInterface $form_state) {
    $entry = $form_state->get('entry');
    $user = $form_state->get('current_uid');
    $entry->field_status = 'allocated_confirmed';
    $entry->save();
    \Drupal::logger('draw_hunting_ballot')->notice('Hunter id: %user accepted Ballot entry %entry block allocation.',
    array(
        '%user' => $user,
        '%entry' => $entry->id(),
    ));
    
    $url = \Drupal\Core\Url::fromUserInput('/donation');
    $form_state->setRedirectUrl($url);

  }
  public function submitFormWithdraw(array &$form, FormStateInterface $form_state) {
    $entry = $form_state->get('entry');
    $user = $form_state->get('current_uid');
    //Release the block allocation
    $release = new ReleaseHuntingBlock($entry);
    $release->releaseblock();

    $entry->field_status = 'withdrawn';
    $entry->save();
    \Drupal::logger('draw_hunting_ballot')->notice('Hunter id: %user withdrew Ballot entry %entry.',
    array(
        '%user' => $user,
        '%entry' => $entry->id(),
    ));

    
    $url = \Drupal\Core\Url::fromRoute('draw_hunting_ballot.user_ballot_entry',['user' => $user]);
    $form_state->setRedirectUrl($url);
    
  }

```
ReleaseHuntingBlock is a method required as this application has a limited number of hunters allowed into any one geographical area at a time, so if a hunting party withdraws, the number in that party has to be decremented from the number allocated to that hunting area.
