### ISSUE TITLE
Default Registration Type Settings - Helpful for sites with 100's of Events

### ISSUE THREAD

**Issue by kclarkson** [dpi/rng#79]
For our website we import up to 100 events every six months so being able to provide "default" settings for each registration type is crucial. 

Here are some default settings we would like to implement. 

-Default relative reminder message based on end date field.  
-Default number of attendees to cap the registration at
-Default Accepting Applications Active

@dpi thank you so much for taking this project on.  Your reputation and contribution to the Drupal community continues to be at a high level.

**Comment by dpi** [comment]
Hi @kclarkson thanks for your kind words :)

> -Default relative reminder message based on end date field.

I dont think I will implement this in the main module ([rationale](https://github.com/dpi/rng/wiki/Solid-Core)). But I don't think it would be too much work to create a separate module to fill this need.

> -Default number of attendees to cap the registration at
> -Default Accepting Applications Active

These two are already possible. You may notice that the form fields located on the Event -> Setting tab are regular Drupal fields attached to your entity type' bundle. All you have to do is set the default field value, and Drupal will autofill these values when your entity is created.

There is a shortcut to the manage fields page on admin/structure/rng/event_types: Operations -> Event Settings defaults. Some screenshots to help:

![event_types___triton](https://cloud.githubusercontent.com/assets/21850/14082830/c6422240-f544-11e5-93c0-0103d2e9338e.jpg)
![list](https://cloud.githubusercontent.com/assets/21850/14082829/c6422b64-f544-11e5-980a-32c1a8ec1af1.jpg)
![maxr](https://cloud.githubusercontent.com/assets/21850/14082828/c640f762-f544-11e5-89e5-7a5253e66f47.jpg)

**Comment by dpi** [comment]
I'm sure you already have seen it, but in case you overlooked it, you can set the date manually for messages on events. But there is not yet a facility to set a default reminder message for newly created events.

**Comment by kclarkson** [comment]
Is it your plan to have this module fully integrated with rules?

So rules should be able to trigger an email based on the registration type!

**Comment by dpi** [comment]
The plan is to integrate around the time Rules receives a UI ~beta ish. You can follow #57 for updates.

**Comment by kclarkson** [comment]
I am closing this based on the fact that two of the three already exists.   Rules integration should be able to accomplish sending email on the registration type's date field.

**Comment by dpi** [comment]
Thanks.

Ive created a feature request for default messages #81. To re-iterate, I dont think the **date field** association will happen in the core module, similar to why [rng_date_scheduler](https://www.drupal.org/project/rng_date_scheduler) exists.
