### ISSUE TITLE
Registration Type States - Attended, Canceled, Did not Show

### ISSUE THREAD

**Issue by kclarkson** [dpi/rng#82]
It would be great to provide a registration "state".  This field should only be visible by event organizers.  This would allow event organizers to mark/flag each registration with attendance data. 

This could theoretically be added with additional modules such as Flag or Field Permissions. 

Unfortunately this would rely on either the flag module or the Field permissions modules where progress for upgrade is either to be determined or no plan at this moment.  

@dpi

**Comment by dpi** [comment]
Hmm, I imagine this could be solved by adding an **attendance** field as a Drupal string list field, in combination with a [field_permissions](https://www.drupal.org/project/field_permissions) -alike. Unless there is something I am missing?

**Comment by kclarkson** [comment]
@dpi based on the comments from the Field Permission's module page it doesn't look like there are any real plans for an upgrade of the module.

**Comment by dpi** [comment]
hence the "-alike". There is progress however... [Port field permissions to drupal 8](https://www.drupal.org/node/2196303). Even if this is not a supported fork, I imagine something has/will fill this functional void since it has 70k installs.

**Comment by dpi** [comment]
Normally state or fields provided/used by RNG are used in some way to calculate interactions between users and an event (registerability). However 'attendance' is not used for this kind of thing, therefore the original request is considered a WONTFIX.
