### ISSUE TITLE
Call to a member function getDefault() on null

### ISSUE THREAD

**Issue by ggd22** [dpi/rng#85]
Getting the error below in Drupal Console running drupal container:debug If I wrap the conditionals on line 85 and 123 in an if($route !== null) error goes away, unsure if this is the correct solution though or why $route is being returned as null.

> $ drupal container:debug
> PHP Fatal error:  Call to a member function getDefault() on null in /var/www/sites/d8/drupal/modules/contrib/rng/src/ContextProvider/RngEventRouteContext.php on line 85
> PHP Stack trace:
> PHP   1. {main}() /usr/local/bin/drupal:0
> PHP   2. require() /usr/local/bin/drupal:10
> PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
> PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/drupal/bin/drupal.php:97
> PHP   5. Drupal\Console\Application->doRun() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:120
> PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/drupal/src/Application.php:282
> PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:189
> PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:846
> PHP   9. Drupal\Console\Command\ContainerDebugCommand->execute() phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php:256
> PHP  10. Drupal\Component\DependencyInjection\Container->get() phar:///usr/local/bin/drupal/src/Command/ContainerDebugCommand.php:45
> PHP  11. Drupal\Component\DependencyInjection\Container->createService() /var/www/sites/d8/drupal/core/lib/Drupal/Component/DependencyInjection/Container.php:181
> PHP  12. Drupal\rng\Cache\Context\RngEventCacheContext->__construct() /var/www/sites/d8/drupal/core/lib/Drupal/Component/DependencyInjection/Container.php:265
> PHP  13. Drupal\rng\ContextProvider\RngEventRouteContext->getRuntimeContexts() /var/www/sites/d8/drupal/modules/contrib/rng/src/Cache/Context/RngEventCacheContext.php:36
> PHP  14. Drupal\rng\ContextProvider\RngEventRouteContext->getEventInRoute() /var/www/sites/d8/drupal/modules/contrib/rng/src/ContextProvider/RngEventRouteContext.php:62

Fatal error: Call to a member function getDefault() on null in /var/www/sites/d8/drupal/modules/contrib/rng/src/ContextProvider/RngEventRouteContext.php on line 85

> Call Stack:
>     0.0001     223024   1. {main}() /usr/local/bin/drupal:0
>     0.0084    1875760   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
>     0.0087    1902040   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
>     0.2497    7135896   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/drupal/bin/drupal.php:97
>     0.2522    7468368   5. Drupal\Console\Application->doRun() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:120
>     1.2498   34114888   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/drupal/src/Application.php:282
>     1.2499   34115608   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:189
>     1.2505   34148824   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:846
>     1.2512   34155824   9. Drupal\Console\Command\ContainerDebugCommand->execute() phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php:256
>     1.7961   57118896  10. Drupal\Component\DependencyInjection\Container->get() phar:///usr/local/bin/drupal/src/Command/ContainerDebugCommand.php:45
>     1.7961   57122056  11. Drupal\Component\DependencyInjection\Container->createService() /var/www/sites/d8/drupal/core/lib/Drupal/Component/DependencyInjection/Container.php:181
>     1.7973   57132096  12. Drupal\rng\Cache\Context\RngEventCacheContext->__construct() /var/www/sites/d8/drupal/core/lib/Drupal/Component/DependencyInjection/Container.php:265
>     1.7973   57132584  13. Drupal\rng\ContextProvider\RngEventRouteContext->getRuntimeContexts() /var/www/sites/d8/drupal/modules/contrib/rng/src/Cache/Context/RngEventCacheContext.php:36
>     1.8033   57308184  14. Drupal\rng\ContextProvider\RngEventRouteContext->getEventInRoute() /var/www/sites/d8/drupal/modules/contrib/rng/src/ContextProvider/RngEventRouteContext.php:62`

**Comment by dpi** [comment]
Thanks for the report. Good to have such detail in these reports.

Fortunately this bug only seems to affect CLI requests.

Committed a bugfix in 3effb26
