### ISSUE TITLE
Deleting a event message leads to an Exception

### ISSUE THREAD

**Issue by edurenye** [dpi/rng#86]
Deleting an event message trows the following exception:

The website encountered an unexpected error. Please try again later.

> Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'canonical' found for the 'rng_rule' entity type in Drupal\Core\Entity\Entity->toUrl() (line 214 of core/lib/Drupal/Core/Entity/Entity.php).
> Drupal\Core\Entity\Entity->urlInfo() (Line: 577)
> content_translation_page_attachments(Array) (Line: 297)
> Drupal\Core\Render\MainContent\HtmlRenderer->invokePageAttachmentHooks(Array) (Line: 273)
> Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
> Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
> Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 111)
> Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 144)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 98)
> Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 77)
> Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
> Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 626)
> Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by dpi** [comment]
This is weird. I don't think content_translation should assume the entity has a [canonical] route.

**Comment by dpi** [comment]
Confirmed issue on 8.0 and 8.1 when installing content_translation

**Comment by edurenye** [comment]
ok, this is a core issue: https://www.drupal.org/node/2479377 and is more related to courier than RNG

**Comment by dpi** [comment]
Thanks for looking into this :)
