### ISSUE TITLE
Issue messaging all registrants on a date

### ISSUE THREAD

**Issue by auVeypor** [dpi/rng#92]
Hey, my team and I have been having an issue getting RNG's "message all registrants on a date" feature working.

The other two options, (users are emailed upon registering and upon updating said registration) work perfectly.

Upon activating a timed message to all registrants, RNG adds the message to the 'rng_rule_scheduler' table just fine, however, RNG fails to ever trigger the rule. The 'attempts' and 'in_queue' columns in the table don't change, and the message is not added to the queue, nor removed from the 'rng_rule_scheduler' table.

We have tested this over several days, the scheduler table is eventually cleaned out, but the message is never queued or sent.

We're using the latest version of RNG and it's associated modules, and Drupal 8.1.0.

If you have any ideas, we'd really appreciate it.

**Comment by dpi** [comment]
Hi @auVeypor, can you check the following:
- The message on your event is enabled. It should say "Send on a date (active)".
- Run cron a couple of times after the date passes. `drush cron`, or there is a link at _/admin/reports/status_.
- Check your site log for errors at _/admin/reports/dblog_

**If you are seeing an error like:**

> Template # for collection # did not validate: The value you selected is not a valid choice.

Then try updating [courier](https://www.drupal.org/project/courier), not RNG, to the version with the fix in dpi/courier@0f961e2

**if your error is different**

then paste the courier or rng related error to this issue.

Let me know if any of these work for you

**Comment by auVeypor** [comment]
Hi @dpi,

We were indeed getting that error.

I have updated courier, and now receive the following error upon clicking the "Add Message" button in an RNG event:

> TypeError: Argument 2 passed to Drupal\courier\Service\CourierManager::__construct() must implement interface Drupal\Core\Config\ConfigFactoryInterface, instance of Drupal\courier\Service\IdentityChannelManager given, called in /mysite/core/lib/Drupal/Component/DependencyInjection/Container.php on line 272 in Drupal\courier\Service\CourierManager->__construct() (line 67 of /mysite/modules/courier/src/Service/CourierManager.php).

I'll try doing a fresh install of Drupal and RNG to test it further tomorrow.

**Comment by dpi** [comment]
Make sure you **clear your cache** and run the **Drupal upgrade** script when updating module code.

Courier's CourierManager injection signature changed since the last stable version. There is also a new entity which needs installing from the upgrade script.

**Comment by dpi** [comment]
Ive just tagged Courier 8.x-1.0-alpha9. You may want to update to it instead of remaining on the -dev track.

**Comment by auVeypor** [comment]
Hey @dpi,

That seems to have fixed the problem, thanks heaps.

One thing we have noticed is the cron requires two runs to dispatch email sent on a date. On the first run the message moves from the scheduler table into the courier queue, and on the second run the queue is cleared and messages dispatched.

Is this intended functionality? Is it possible to configure courier to dispatch the emails upon a single cron run? We'd prefer the bulk mails to be sent ASAP upon triggering the rule.

**Comment by dpi** [comment]
> One thing we have noticed is the cron requires two runs to dispatch email sent on a date. [...] Is it possible to configure courier to dispatch the emails upon a single cron run?

Ive got a feeling that it can, but it may be random/site dependent. It has something to do with the hook invocation order: https://www.drupal.org/node/110238 . In this case you would want RNG' `hook_cron()` to run before Couriers.

I've created #93 to address this issue. In the interim, you could make your cron script trigger every minute/30 seconds?

**Comment by auVeypor** [comment]
Thanks a ton for all your help, really appreciate it.
