### ISSUE TITLE
All messages for an event are queued if just one message reaches its scheduled date

### ISSUE THREAD

**Issue by auVeypor** [dpi/rng#94]
Hey @dpi,

We have encountered what we believe to be unintended behaviour with the messaging system.

Upon adding two or more "message all applicants on a date" messages to the same event, upon the date trigger for one of these messages, **ALL** active messages are dispatched immediately, despite the other active messages not being due to be sent.

This even triggers upon a disabled message meeting it's set date. If we add a disabled message and set it to be due in a minute's time, even though that message is disabled still, it will trigger **ALL** active messages to be sent nonetheless.

We believe this to be unintended behaviour. As far as we can tell, RNG should only send the single message upon the date that message is set to be sent.

Are we configuring this incorrectly, or is this a defect?

**Comment by dpi** [comment]
I'll look into it.

**Comment by dpi** [comment]
> ALL active messages are dispatched immediately,

site wide? or for the single event?

**Comment by auVeypor** [comment]
We didn't test multiple events, give me 5 minutes and ill test it.

**Comment by auVeypor** [comment]
It's just for the single event. All active mail for an event is dispatched upon a single trigger being met.

**Comment by auVeypor** [comment]
Any ideas @dpi?

I'd be happy to have a stab at it myself and submit a pull request if you point me in the right direction.

**Comment by dpi** [comment]
Hadnt had time to look into it. I usually update the issue if I'm active.

Likely has something to do with the cron hook.

**Comment by dpi** [comment]
> This even triggers upon a disabled message meeting it's set date.

I can see there is an issue with enabled/disabled messages.

But I cannot reproduce **all** messages being sent if one reaches a date.

**Steps** 
1. Create a message with a message to send one week ago. Activate the message.
2. Create a message with a message to send one week in the future. Activate the message.
3. Run cron, a few times just in case.

**Result:** only one message is sent.

**Comment by dpi** [comment]
I think I have found the issue, and it was quite an annoying one to track down. Can you try out the dev release and see if it fixes things for you.

One thing you may notice is that a message will be disabled as soon as the message has been queued by cron.

**Comment by auVeypor** [comment]
That seems to have fixed it, thanks!

**Comment by dpi** [comment]
Fantastic. This will be bundled with rng-8.0-1.2
