### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ghost** [dpi/rng#96]
Its damn great that you created this module and related ecosystem around the module. To do this all by yourself is something remarkable achievement. Well, I'd like to thank you very much for it, I'm still having hard time to grasp some design concepts and methods you used but I very much appreciate a hard work you have done.

Once again thank you for such a great work where the community can benefit.

I feel only thing is missing is a through tutorial how you'd implement an event and registration, or some showcase examples, or step by step how to do, blogs videos, etc. This module is great but users would use it to its potential when there is good guidance how to use it.

I have checked your blog and drupal answers in stack exchange channel about RNG, its great in itself but I hope lot more to come.

BR
Rajib

**Comment by dpi** [comment]
Thanks for your kind words :)

I can only hope educational material become available organically as module usage grows.

Making requests to sites like Drupalize.me or OSTraining could also accelerate the creation of these materials.
