### ISSUE TITLE
Anonymous User Initiative

### ISSUE THREAD

**Issue by dpi** [dpi/rng#99]
Discussions at #89: Support registration for anonymous users

**Collection of issues related to implementation of anonymous users.**
- ~~#90 **registrant entity CRUD routes:** Need a way to add identity metadata to the registration since the anonymous entity is recycled.~~
-  ~~#100 **Show entity label instead of autocomplete if only one entity is registerable**. The anonymous entity type should only have one entity, so this issue is a UX improvement for the anon entity type.~~
- #102 **Provide ability to edit the registrant inline with registration**

**Comment by dpi** [comment]
Probably 1.3

**Comment by javieraldape** [comment]
Hi, i'm interested in this feature. Do you have an expected release date?

**Comment by dpi** [comment]
Re #89 

@javieraldape I'm currently doing it in my spare time, hopefully this year. If [sponsored](https://dpi.id.au/drupal-sponsor/) then within a week.

**Comment by dpi** [comment]
See #89
